// parse_bo_pdf.js
// Node script that reads a BO PDF (generated by fetch_bo_pdf.js) and extracts a CSV.
// Usage: node parse_bo_pdf.js <pdfFile>
// Example: node parse_bo_pdf.js bo_1208_859559.pdf

const fs = require('fs');
const pdf = require('pdf-parse');

const [,, pdfPath] = process.argv;
if (!pdfPath) {
  console.error('Usage: node parse_bo_pdf.js <pdfFile>');
  process.exit(1);
}

fs.readFile(pdfPath, async (err, data) => {
  if (err) {
    console.error('Failed to read PDF:', err);
    process.exit(1);
  }
  try {
    const { text } = await pdf(data);
    const lines = text.split('\n').filter(l => l.trim());
    // Heuristic: locate the header line that contains the word "Vlastník" (owner)
    const headerIdx = lines.findIndex(l => /Vlastník/i.test(l));
    if (headerIdx === -1) {
      console.error('Could not find owner table header in PDF.');
      process.exit(1);
    }
    const tableLines = lines.slice(headerIdx).filter(l => l.trim());
    // Convert multiple spaces into a single comma for CSV
    const csvRows = tableLines.map(row => row.replace(/\s{2,}/g, ',').trim());
    const csvContent = csvRows.join('\n');
    const outCsv = pdfPath.replace(/\.pdf$/i, '.csv');
    fs.writeFileSync(outCsv, csvContent, 'utf8');
    console.log(`✅ CSV written to ${outCsv}`);
  } catch (e) {
    console.error('PDF parsing error:', e);
    process.exit(1);
  }
});
